FROM golang:1.18 AS build
WORKDIR /go/src/github.com/salesforce/UniTAO/
COPY . ./
RUN go build -a -o ./bin/ ./app/DataService
RUN go build -a -o ./bin/ ./tool/DataServiceAdmin
COPY ./tool/DataServiceAdmin/initTable.sh ./bin/

FROM centos:latest
WORKDIR /opt/UniTAO/
ENV PATH="/opt/UniTAO/:${PATH}"
COPY --from=build /go/src/github.com/salesforce/UniTAO/bin/. ./
RUN mkdir ./config
RUN mkdir ./schema
RUN echo 'alias ll="ls -alF"' >> ~/.bashrc
COPY --from=build /go/src/github.com/salesforce/UniTAO/dbSchemas/DynamoDB/Tables.json ./schema/
COPY --from=build /go/src/github.com/salesforce/UniTAO/lib/Schema/data/schema.json ./schema/